version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      composer-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
